export const LOAD_SUCCESS = 'LOAD_SUCCESS';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const DELETE = 'DELETE';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_ERROR = 'DELETE_ERROR';

export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_TYPES_SUCCESS = 'LOAD_TYPES_SUCCESS';

export const CLEAR_ERROR = 'CLEAR_ERROR';
